"""Domain models — pure data, no I/O.

All classes are frozen Pydantic `BaseModel` instances so they are
immutable, hashable (where useful), and serialisable to JSON.
"""

from __future__ import annotations

import datetime as _dt
from typing import Annotated, Any

from pydantic import BaseModel, BeforeValidator, Field


# ── helpers ───────────────────────────────────────────────────────

def _now_iso(value: Any) -> str:  # noqa: ARG001 — value is the raw input; we always override
    return _dt.datetime.now(_dt.timezone.utc).isoformat()


# ── VideoMetadata (from ffprobe) ─────────────────────────────────

class VideoMetadata(BaseModel, frozen=True):
    """Result of probing a video file with ffprobe.

    All fields except ``duration_s`` are optional because some streams
    may not carry every piece of metadata.
    """

    capture_time: _dt.datetime | None = None  # embedded QuickTime EXIF time
    date_source: str = "file"               # "embedded" or "file" fallback
    duration_s: float
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    codec: str | None = None
    has_audio: bool = False


# ── Clip (main entity) ───────────────────────────────────────────

class Clip(BaseModel):
    """Persisted record for one video clip.

    ``source_path`` is the read-only original; ``library_path`` points
    to its copy in the organised library.  No I/O touches these fields
    directly — only ``ClipRepository`` does persistence.
    """

    id: int | None = None
    fingerprint: str  # sha256 of size + first 4 MiB (dedup key)
    source_path: str  # original file, never modified

    library_path: str | None = None
    roll_type: str  # "a" or "b" (RollType)
    roll_source: str = "auto"  # "auto" or "manual" (Source)

    capture_time: _dt.datetime | None = None
    date_source: str = "file"  # DateSource

    duration_s: float | None = None
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    codec: str | None = None

    thumbnail_path: str | None = None  # relative to <library>/.cutfinder/

    summary: str | None = None   # A-roll Chinese intro (from summariser)
    description: str | None = None  # B-roll visual description (from vision tagger)

    status: str = "pending"  # ClipStatus
    error: str | None = None

    created_at: Annotated[str, BeforeValidator(_now_iso)]  # ISO timestamp
    processed_at: str | None = None


# ── ClipSummary (lightweight for listing / queries) ───────────────

class ClipSummary(BaseModel):
    """Slimmed-down view of a clip, used for list queries and API responses."""

    id: int
    source_path: str
    library_path: str | None = None
    roll_type: str  # "a" or "b"
    summary: str | None = None
    description: str | None = None
    duration_s: float | None = None
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    codec: str | None = None
    thumbnail_path: str | None = None
    status: str  # ClipStatus
    error: str | None = None
    capture_time: _dt.datetime | None = None
    date_source: str  # DateSource


# ── Tag (per-clip) ───────────────────────────────────────────────

class Tag(BaseModel, frozen=True):
    """A tag on a clip — auto-generated by AI or manually added by the user."""

    name: str
    source: str  # "auto" or "manual" (Source)


# ── Transcript / Segment (A-roll only) ───────────────────────────

class Segment(BaseModel, frozen=True):
    start_s: float
    end_s: float
    text: str


class Transcript(BaseModel, frozen=True):
    full_text: str = ""
    segments: list[Segment] = []


# ── SummaryResult (A-roll AI output) ─────────────────────────────

class SummaryResult(BaseModel, frozen=True):
    summary: str  # Chinese intro
    tags: list[str]


# ── VisionResult (B-roll AI output) ─────────────────────────────

class VisionResult(BaseModel, frozen=True):
    description: str  # Chinese visual description
    tags: list[str]


# ── AnalysisResult (combined AI output) ─────────────────────────

class AnalysisResult(BaseModel, frozen=True):
    """Full output from the per-clip analysis pipeline."""

    roll_type: str  # "a" or "b"
    transcript: Transcript | None = None       # A-roll only (None for B)
    summary_result: SummaryResult | None = None  # A-roll only (None for B)
    vision_result: VisionResult | None = None  # B-roll only (None for A)


# ── ClipFilter (query parameters for list/search) ───────────────

class ClipFilter(BaseModel, frozen=True):
    """Query parameters for filtering clips in the catalog."""

    date: str | None = None       # ISO date "YYYY-MM-DD"
    roll_type: str | None = None  # "a", "b", or None for all
    tag: str | None = None        # exact match on tag name


# ── ClipCandidate (Scanner output) ───────────────────────────────

class ClipCandidate(BaseModel, frozen=True):
    """A single file discovered by the scanner that needs processing.

    Produced by :meth:`~Scanner.scan`; consumed by the pipeline orchestrator.
    ``fingerprint`` is a sha256 hex digest used for deduplication against the
    catalog database.

    Examples
    --------
    >>> c = ClipCandidate(path="/tmp/clip.mp4", fingerprint="abc123")
    >>> c.path
    '/tmp/clip.mp4'

    Tracker for call assertions in tests:

        path :: Path
            The absolute or relative file system path to the clip.
    """

    path: Annotated[str, Field(min_length=1)]  # filesystem path (absolute or relative)
    fingerprint: Annotated[  # sha256 hex digest for deduplication
        str, Field(pattern=r"^[0-9a-f]+$"),
    ]


# ── Job (queue job tracking) ─────────────────────────────────────

class Job(BaseModel, frozen=True):
    """Represents a scan+process job in the queue."""

    id: int | None = None
    status: str  # JobStatus (running / done / failed)
    total: int = 0
    done: int = 0
    failed: int = 0
    started_at: str | None = None
    finished_at: str | None = None
