"""Domain models — pure data, no I/O.

All classes are frozen Pydantic `BaseModel` instances so they are
immutable, hashable (where useful), and serialisable to JSON.
"""

from __future__ import annotations

import datetime as _dt
from typing import Annotated, Any

from pydantic import BaseModel, BeforeValidator, Field


# ── helpers ───────────────────────────────────────────────────────

def _now_iso(value: Any) -> str:  # noqa: ARG001 — value is the raw input; we always override
    return _dt.datetime.now(_dt.timezone.utc).isoformat()


# ── VideoMetadata (from ffprobe) ─────────────────────────────────

class VideoMetadata(BaseModel, frozen=True):
    """Result of probing a video file with ffprobe.

    All fields except ``duration_s`` are optional because some streams
    may not carry every piece of metadata.
    """

    capture_time: _dt.datetime | None = None  # embedded QuickTime EXIF time
    date_source: str = "file"               # "embedded" or "file" fallback
    duration_s: float
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    codec: str | None = None
    has_audio: bool = False


# ── Clip (main entity) ───────────────────────────────────────────

class Clip(BaseModel):
    """Persisted record for one video clip.

    ``source_path`` is the read-only original; ``library_path`` points
    to its copy in the organised library.  No I/O touches these fields
    directly — only ``ClipRepository`` does persistence.
    """

    id: int | None = None
    fingerprint: str  # sha256 of size + first 4 MiB (dedup key)
    source_path: str  # original file, never modified

    library_path: str | None = None
    roll_type: str  # "a" or "b" (RollType)
    roll_source: str = "auto"  # "auto" or "manual" (Source)

    capture_time: _dt.datetime | None = None
    date_source: str = "file"  # DateSource

    duration_s: float | None = None
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    codec: str | None = None

    thumbnail_path: str | None = None  # relative to <library>/.cutfinder/

    summary: str | None = None   # A-roll Chinese intro (from summariser)
    description: str | None = None  # B-roll visual description (from vision tagger)

    status: str = "pending"  # ClipStatus
    error: str | None = None

    created_at: Annotated[str, BeforeValidator(_now_iso)]  # ISO timestamp
    processed_at: str | None = None


# ── ClipSummary (lightweight for listing / queries) ───────────────

class ClipSummary(BaseModel):
    """Slimmed-down view of a clip, used for list queries and API responses."""

    id: int
    source_path: str
    library_path: str | None = None
    roll_type: str  # "a" or "b"
    summary: str | None = None
    description: str | None = None
    duration_s: float | None = None
    width: int | None = None
    height: int | None = None
    fps: float | None = None
    codec: str | None = None
    thumbnail_path: str | None = None
    status: str  # ClipStatus
    error: str | None = None
    capture_time: _dt.datetime | None = None
    date_source: str  # DateSource
    has_keyframes: bool = False  # True if the clip has keyframe suggestions


# ── Tag (per-clip) ───────────────────────────────────────────────

class Tag(BaseModel, frozen=True):
    """A tag on a clip — auto-generated by AI or manually added by the user."""

    name: str
    source: str  # "auto" or "manual" (Source)


# ── Transcript / Segment (A-roll only) ───────────────────────────

class Segment(BaseModel, frozen=True):
    start_s: float
    end_s: float
    text: str


class Transcript(BaseModel, frozen=True):
    full_text: str = ""
    segments: list[Segment] = []


# ── SubtitleRequest (standalone subtitle export) ─────────────────

class SubtitleRequest(BaseModel, frozen=True):
    """Request to re-transcribe a finished video and export subtitle files."""

    video_path: str
    out_dir: str
    formats: list[str] = ["itt", "srt"]
    language: str = "zh"
    # Minimum on-screen seconds per cue (0 = keep transcribed timing).
    min_cue_s: float = 0.0


# ── SummaryResult (A-roll AI output) ─────────────────────────────

class SummaryResult(BaseModel, frozen=True):
    summary: str  # Chinese intro
    tags: list[str]


# ── VisionResult (B-roll AI output) ─────────────────────────────

class VisionResult(BaseModel, frozen=True):
    description: str  # Chinese visual description
    tags: list[str]


# ── CutSuggestion (keyframe recommendation) ─────────────────────

class CutSuggestion(BaseModel, frozen=True):
    """A recommended edit cut window + representative frame for a clip.

    Produced by the keyframe-recommendation step: A-roll suggestions come from
    the text model reasoning over transcript segments (``source="text"``),
    B-roll from the vision model judging sampled frames (``source="vision"``).
    """

    rank: int                       # 1 = best
    start_s: float                  # in-point (seconds)
    end_s: float                    # out-point (seconds)
    reason: str = ""                # one-line rationale (AI output language)
    frame_path: str | None = None   # representative frame image (absolute path)
    source: str = "vision"          # "text" (A-roll) | "vision" (B-roll)


# ── Rough-cut agent (§3.15) ─────────────────────────────────────

class RoughCutRequest(BaseModel, frozen=True):
    """Parsed parameters for a rough-cut request (free-form style as text).

    The conversational agent derives these from the user's message; all
    fields are optional so a partial request still works.
    """

    date_from: str | None = None     # ISO "YYYY-MM-DD" (inclusive)
    date_to: str | None = None       # ISO "YYYY-MM-DD" (inclusive)
    target_min_s: float | None = None
    target_max_s: float | None = None
    aspect_ratio: str = "16:9"
    style_notes: str = ""            # free-text style / rhythm description


class ClipBrief(BaseModel, frozen=True):
    """Lightweight catalog row the agent searches over (one footage candidate)."""

    clip_id: int
    roll: str                        # "a" | "b"
    capture_time: str | None = None  # ISO string
    duration_s: float | None = None
    summary: str | None = None       # A-roll intro
    description: str | None = None   # B-roll visual description
    tags: list[str] = []
    has_transcript: bool = False
    has_keyframes: bool = False


class ClipDetail(BaseModel, frozen=True):
    """Full per-clip detail the agent pulls when composing in/out points."""

    clip_id: int
    roll: str
    duration_s: float | None = None
    capture_time: str | None = None        # ISO capture time (shooting date source)
    source_path: str | None = None         # read-only original
    library_path: str | None = None        # organised copy (for the file label)
    summary: str | None = None
    description: str | None = None
    tags: list[str] = []
    segments: list[Segment] = []           # A-roll transcript segments
    keyframes: list[CutSuggestion] = []    # existing keyframe cut points


class Shot(BaseModel, frozen=True):
    """One row of the shot list — a sub-clip in/out window with rationale."""

    clip_id: int
    roll: str                        # "a" | "b"
    in_s: float
    out_s: float
    content: str = ""                # 台词 / 画面内容
    rationale: str = ""              # 用途 · 理由
    chapter: str = ""                # chapter / section title
    clip_label: str = ""             # library/source file name (filled by director)
    clip_date: str = ""              # ISO shooting date YYYY-MM-DD (filled by director)
    thumb_ref: str | None = None     # thumbnail URL (filled by the director)


class CutPlan(BaseModel, frozen=True):
    """A generated shot list with chapter grouping and a duration roll-up."""

    shots: list[Shot] = []
    chapters: list[str] = []         # ordered unique chapter titles
    total_s: float = 0.0
    target_min_s: float | None = None
    target_max_s: float | None = None
    within_target: bool = True       # False → footer flags "missed target"
    note: str = ""                   # assistant note (e.g. duration warning)


class ChatMessage(BaseModel, frozen=True):
    """One persisted message in a rough-cut conversation."""

    role: str                        # "user" | "assistant" | "tool"
    content: str = ""
    tool_json: str | None = None     # raw tool_calls / tool_result (optional)
    created_at: str | None = None


class CutSession(BaseModel):
    """A persisted rough-cut conversation (reopenable, deletable)."""

    id: int | None = None
    title: str = ""
    status: str = "idle"             # "idle" | "running" | "error"
    # Live, human-readable progress while a turn runs (e.g. "第 2/6 天 · 查看片段
    # #123 台词"). Ephemeral — held in memory by the store, not persisted; the
    # polling UI reads it to show what the director is doing right now.
    progress: str = ""
    created_at: str | None = None
    updated_at: str | None = None


# ── AnalysisResult (combined AI output) ─────────────────────────

class AnalysisResult(BaseModel, frozen=True):
    """Full output from the per-clip analysis pipeline."""

    roll_type: str  # "a" or "b"
    transcript: Transcript | None = None       # A-roll only (None for B)
    summary_result: SummaryResult | None = None  # A-roll only (None for B)
    vision_result: VisionResult | None = None  # B-roll only (None for A)


# ── ClipFilter (query parameters for list/search) ───────────────

class ClipFilter(BaseModel, frozen=True):
    """Query parameters for filtering clips in the catalog."""

    date: str | None = None       # ISO date "YYYY-MM-DD"
    roll_type: str | None = None  # "a", "b", or None for all
    tag: str | None = None        # exact match on tag name


# ── ClipCandidate (Scanner output) ───────────────────────────────

class ClipCandidate(BaseModel, frozen=True):
    """A single file discovered by the scanner that needs processing.

    Produced by :meth:`~Scanner.scan`; consumed by the pipeline orchestrator.
    ``fingerprint`` is a sha256 hex digest used for deduplication against the
    catalog database.

    Examples
    --------
    >>> c = ClipCandidate(path="/tmp/clip.mp4", fingerprint="abc123")
    >>> c.path
    '/tmp/clip.mp4'

    Tracker for call assertions in tests:

        path :: Path
            The absolute or relative file system path to the clip.
    """

    path: Annotated[str, Field(min_length=1)]  # filesystem path (absolute or relative)
    fingerprint: Annotated[  # sha256 hex digest for deduplication
        str, Field(pattern=r"^[0-9a-f]+$"),
    ]


# ── Job (queue job tracking) ─────────────────────────────────────

class Job(BaseModel, frozen=True):
    """Represents a scan+process job in the queue."""

    id: int | None = None
    status: str  # JobStatus (queued / running / done / failed / cancelled)
    kind: str = "scan"  # "scan" | "reanalyze"
    total: int = 0
    done: int = 0
    failed: int = 0
    started_at: str | None = None
    finished_at: str | None = None


# ── JobFailedItem (per-item failure record for retry) ────────────

class JobFailedItem(BaseModel, frozen=True):
    """A single failed queue item, recorded so a job can be retried."""

    job_id: int
    kind: str                      # "clip" | "reanalyze"
    path: str | None = None        # ClipCandidate.path  (kind="clip")
    fingerprint: str | None = None  # ClipCandidate.fingerprint (kind="clip")
    clip_id: int | None = None     # (kind="reanalyze")
    error: str | None = None
